POST http://[::1]:3333/register
Content-Type: application/json

{ 
  "name": "Maria",
  "email": "mariajoaquina@gmail.com", 
  "password": "senha123"
}

###

GET http://[::1]:3333/users

###

POST http://[::1]:3333/login
Content-Type: application/json

{ 
  "email": "joaogamer@gmail.com",
  "password": "senha123" 
}

###

GET http://[::1]:3333/tasks/1

###

POST http://[::1]:3333/createtask/1
Content-Type: application/json

{
  "tittle": "Tirar o lixo",
  "content": "Tem que tirar o lixo até amanha"
}

###

DELETE http://[::1]:3333/deletetask/1/6

###

PUT http://[::1]:3333/completed/1/2

###

POST http://[::1]:3333/search/1
Content-Type: application/json

{
  "search": "a"
}